apiVersion: 0.0.1
kind: ksonnet.io/app
libraries:
  argo:
    gitVersion:
      commitSha: 30f913986607bb8414d51ef6a23fe60fec9afe3c
      refSpec: master
    name: argo
    registry: kubeflow
  core:
    gitVersion:
      commitSha: 30f913986607bb8414d51ef6a23fe60fec9afe3c
      refSpec: master
    name: core
    registry: kubeflow
  seldon:
    gitVersion:
      commitSha: 30f913986607bb8414d51ef6a23fe60fec9afe3c
      refSpec: master
    name: seldon
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 30f913986607bb8414d51ef6a23fe60fec9afe3c
      refSpec: master
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: 30f913986607bb8414d51ef6a23fe60fec9afe3c
      refSpec: master
    name: tf-serving
    registry: kubeflow
name: ks_kubeflow_seldon
registries:
  incubator:
    gitVersion:
      commitSha: 422d521c05aa905df949868143b26445f5e4eda5
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 30f913986607bb8414d51ef6a23fe60fec9afe3c
      refSpec: master
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
